services:
  # Сервис базы данных
  db:
    image: postgres:15
    container_name: wishlist-postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_INSIDE_PORT}"  # Оставляем порт N наружу для твоего ПК, если захочешь подключиться
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 5

  db-test:
    image: postgres:15
    container_name: wishlist-postgres-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: pet_wishlist_test_db  # Новое имя тестовой БД
    ports:
      - "5434:5432" # Внешний порт 5434

  # Сервис нашего FastAPI приложения
  web:
    build: .
    container_name: wihslist-app
    ports:
      - "${APP_EXTERNAL_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy   # Запускать приложение только после старта базы данных

volumes:
  postgres_data:  # Хранилище, чтобы данные пользователей не удалялись при перезапуске контейнеров
